sonar.projectKey=ecommerce-lp2
sonar.projectName=E-commerce LP2 2024
sonar.projectVersion=1.0.0
sonar.sourceEncoding=UTF-8

# Paths
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes

# Coverage
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.java.coveragePlugin=jacoco

# Exclusions
sonar.exclusions=**/config/**,**/dto/**
sonar.test.exclusions=src/test/**

# Quality Gates
sonar.qualitygate.wait=true
